config/routes.rb
Rails.application.routes.draw do
  # resources :stocks
 # get #'home/index'
  namespace :api do 
    namespace :v1 do
      resources :stocks
    end
  end
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  #get "/auth/:provider/callback", to: "rodauth#omniauth"
  # Defines the root path route ("/")
  root "stocks#index"
  scope '/dashboard' do 
    get "/dashboard", to: "stocks#index"
    resources :stocks
  end
end

app/models/account.rb
class Account < ApplicationRecord
  include Rodauth::Rails.model
  enum :status, unverified: 1, verified: 2, closed: 3
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/link.rb
Link = Struct.new(:title, :path)

app/models/stock.rb
class Stock < ApplicationRecord
  validates :product_name, presence: true
  validates :quantity, presence: true
  validates :description, presence: true
  validates :price, presence: true
  paginates_per 5
     def self.ransackable_attributes(auth_object = nil)
    ["created_at", "description", "id", "price", "product_name", "quantity", "updated_at"]
  end
end

app/controllers/api/v1/api_controller.rb
module Api
  module V1
    class ApiController < ActionController::Base
    
    end
  end
end

app/controllers/api/v1/stocks_controller.rb
module Api
  module V1
    class StocksController < ApiController
      def index
            @stocks = Stock.all
            puts "testing", @stocks
            render json: {status: 'SUCCESS', message: 'Loaded stocks', data:@stocks}, status: :ok
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include Pundit::Authorization
    after_action :verify_authorized, except: :index

    before_action :initialize_breadcrumb
    after_action :verify_policy_scoped, only: :index

    rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

    around_action :switch_locale
    
 # Overwrite unverified request handler to force a refresh / redirect.
  def handle_unverified_request
    redirect_to request.referrer
  end

  def user_not_authorized
      flash[:alert] = I18n.t("errors.unauthorized")
      redirect_back_or_to root_path, allow_other_host: false
      rescue ActionController::Redirecting::UnsafeRedirectError
      redirect_to root_path
  end

  #Setting the Locale from User Preferences
  def switch_locale(&action)
    locale = current_account.try(:locale) || I18n.default_locale
    I18n.with_locale(locale, &action)
  end

  
  def default_url_options
    { locale: I18n.locale }
  end
  
  protected

    def authenticate
        rodauth.require_account # redirect to login page if not authenticated
    end

    def pundit_user
        current_account
    end

    def initialize_breadcrumb
        @breadcrumb_active_page = ""
        @breadcrumb_hash = {}
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/rodauth_controller.rb
class RodauthController < ApplicationController
  # used by Rodauth for rendering views, CSRF protection, and running any
  # registered action callbacks and rescue_from handlers
    skip_after_action :verify_authorized

  layout :rodauth_layout

  def omniauth
    auth = request.env["omniauth.auth"]

    # attempt to find existing identity directly
    identity = AccountIdentity.find_by(provider: auth["provider"], uid: auth["uid"])

    if identity
      # update any external info changes
      identity.update!(info: auth["info"])
      # set account from identity
      account = identity.account
    end

    # attempt to find an existing account by email
    account ||= Account.find_by(email: auth["info"]["email"])

    # disallow login if account is not verified
    if account && account.status != rodauth.account_open_status_value
      redirect_to rodauth.login_path, alert: rodauth.unverified_account_message
      return
    end

    # create new account if it doesn't exist
    unless account
      account = Account.create!(email: auth["info"]["email"], status: rodauth.account_open_status_value)
    end

    # create new identity if it doesn't exist
    unless identity
      account.identities.create!(provider: auth["provider"], uid: auth["uid"], info: auth["info"])
    end

    # load the account into the rodauth instance
    rodauth.account_from_login(account.email)

    rodauth_response do # ensures any `after_action` callbacks get called
      # sign in the loaded account
      rodauth.login("omniauth")
    end
  end

  private

  def rodauth_layout
    case request.path
    when rodauth.login_path,
         rodauth.create_account_path,
         rodauth.verify_account_path,
         rodauth.reset_password_path,
         rodauth.reset_password_request_path
      "account"
    else
      "dashboard"
    end
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :set_stock, only: %i[ show edit update destroy ]
  skip_after_action :verify_policy_scoped, only: :index
  skip_after_action :verify_authorized, except: :index
  before_action :authenticate

  # GET /stocks or /stocks.json
  def index
    @q = Stock.ransack(params[:q])
    @stocks = @q.result(distinct: true).page params[:page]
    # @stocks = Stock.all
  end

  # GET /stocks/1 or /stocks/1.json
  def show
  end

  # GET /stocks/new
  def new
    @stock = Stock.new
    render turbo_stream: turbo_stream.update("model", partial: "shared/form", locals: {url: stocks_path,object: Stock.new})
  end

  # GET /stocks/1/edit
  def edit
    render turbo_stream: turbo_stream.update("model", partial: "shared/form", locals: {url: stock_path,object: @stock})
  end

  # POST /stocks or /stocks.json
  def create
    @stock = Stock.new(stock_params)
    @stock.account_id = current_account.id
    respond_to do |format|
      if @stock.save
        format.html { redirect_to stocks_path, notice: "Stock was successfully created." }
        format.turbo_stream { }
      else
        format.html { render :new, status: :unprocessable_entity }
       format.turbo_stream { }
      end
    end
  end

  # PATCH/PUT /stocks/1 or /stocks/1.json
  def update
    respond_to do |format|
      if @stock.update(stock_params)
      index
        format.html { redirect_to stocks_url, notice: "Stock was successfully updated." }
        format.json { render :show, status: :ok, location: @stock }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stocks/1 or /stocks/1.json
  def destroy
    @stock.destroy

    respond_to do |format|
      format.html { redirect_to stocks_url, notice: "Stock was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stock
      @stock = Stock.find(params[:id])

    end

    # Only allow a list of trusted parameters through.
    def stock_params
      params.require(:stock).permit(:product_name, :description, :quantity, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/home/index.html.erb
<div>
  <h1 class="font-bold text-4xl">Home#index</h1>
  
</div>

app/views/layouts/account.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Inventory</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="flex min-h-full flex-col justify-center py-12 sm:px-6 lg:px-8">
        <div class="sm:mx-auto sm:w-full sm:max-w-md">
            <img class="mx-auto h-12 w-auto" src="https://tailwindui.com/img/logos/mark.svg?color=indigo&shade=600" alt="Your Company">
            <%= yield :header %>
        </div>

        <div class="mt-8 sm:mx-auto sm:w-full sm:max-w-md">
            <div class="bg-white py-8 px-4 shadow sm:rounded-lg sm:px-10">
            <%= yield :form %>
            </div>
        </div>
        </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="h-full bg-gray-100">
  <head>
    <title>Inventory</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://rsms.me/inter/inter.css">
    <link rel="stylesheet" href="https://ga.jspm.io/npm:flatpickr@4.6.9/dist/flatpickr.min.css">
    <script src="//unpkg.com/alpinejs"></script>
  </head>

  <body class="h-full" x-data="{'isModalOpen': false}" x-on:keydown.escape="isModalOpen=false" >
    <div class="min-h-full">
    <%= render Dashboard::TopBarComponent.new %>
      <div class="py-10">
        
        <main>
          <div class="mx-auto max-w-7xl sm:px-6 lg:px-8">
            <!-- Your content --><%= yield :header%>
            <%= yield :content%>
          </div>
        </main>
      </div>
    </div>
  </body>
   <%= render "shared/model" , object: Stock.new, url: stocks_path %>
</html>

app/views/rodauth/_login_form.html.erb
<% content_for(:header) do %>
    <h2 class="mt-6 text-center text-3xl font-bold tracking-tight text-gray-900">Sign in to your account</h2>
    <p class="mt-2 text-center text-sm text-gray-600">
      Or
      <%= link_to "Sign Up", rodauth.create_account_path, class: "font-medium text-indigo-600 hover:text-indigo-500" %>
    </p>
<%end%>
<% content_for(:form) do %>
  <%= form_with url: rodauth.login_path, method: :post, data: { turbo: false }, class: "w-full max-w-sm" do |form| %>
    <% if rodauth.skip_login_field_on_login? %>
      <div class="mb-6">
        <%= form.label "login", rodauth.login_label, class: "block text-sm font-semibold" %>
        <%= form.email_field rodauth.login_param, value: params[rodauth.login_param], id: "login", readonly: true, class: "mt-2 text-sm w-full py-2 px-0 bg-inherit border-transparent focus:ring-0 focus:border-transparent" %>
      </div>
    <% else %>
      <div class="mb-6">
        <%= form.label "login", rodauth.login_label, class: "block text-sm font-semibold" %>
        <%= form.email_field rodauth.login_param, value: params[rodauth.login_param], id: "login", autocomplete: "email", required: true, class: "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm #{rodauth.field_error(rodauth.login_param) ? "border-red-600 focus:ring-red-600 focus:border-red-600 dark:border-red-400 dark:focus:ring-red-400" : "ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" }", aria: ({ invalid: true, describedby: "login_error_message" } if rodauth.field_error(rodauth.login_param)) %>
        <%= content_tag(:span, rodauth.field_error(rodauth.login_param), class: "block mt-1 text-red-600 text-xs dark:text-red-400", id: "login_error_message") if rodauth.field_error(rodauth.login_param) %>
      </div>
    <% end %>

    <% unless rodauth.skip_password_field_on_login? %>
      <div class="mb-6">
        <%= form.label "password", rodauth.password_label, class: "block text-sm font-semibold" %>
        <%= form.password_field rodauth.password_param, value: "", id: "password", autocomplete: rodauth.password_field_autocomplete_value, required: true, class: "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm #{rodauth.field_error(rodauth.password_param) ? "border-red-600 focus:ring-red-600 focus:border-red-600 dark:border-red-400 dark:focus:ring-red-400" : "ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" }", aria: ({ invalid: true, describedby: "password_error_message" } if rodauth.field_error(rodauth.password_param)) %>
        <%= content_tag(:span, rodauth.field_error(rodauth.password_param), class: "block mt-1 text-red-600 text-xs dark:text-red-400", id: "password_error_message") if rodauth.field_error(rodauth.password_param) %>
      </div>
    <% end %>

    <div class="flex items-center justify-between mb-10">
      <div class="flex items-center">
        <input id="remember-me" name="remember-me" type="checkbox" class="h-4 w-4 rounded border-gray-300 text-indigo-600 focus:ring-indigo-600">
        <label for="remember-me" class="ml-2 block text-sm text-gray-900">Remember me</label>
      </div>

      <div class="text-sm">
        <%= link_to "Forgot your password?", rodauth.reset_password_request_path, class: "font-medium text-indigo-600 hover:text-indigo-500"%>
      </div>
    </div>

    <%= form.submit rodauth.login_button, class: "flex w-full justify-center rounded-md bg-indigo-600 py-2 px-3 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600" %>
  <% end %>
<% end %>

app/views/rodauth/_login_form_footer.html.erb
<% unless rodauth.login_form_footer_links.empty? %>
  <ul>
    <% rodauth.login_form_footer_links.sort.each do |_, link, text| %>
      <li><%= link_to text, link, class: "text-blue-600 rounded-sm text-sm hover:underline hover:text-blue-800 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-600 dark:text-blue-300 dark:hover:text-blue-400 dark:focus-visible:ring-2 dark:focus-visible:ring-blue-300" %></li>
    <% end %>
  </ul>
<% end %>

app/views/rodauth/_login_form_header.html.erb
<% if rodauth.field_error(rodauth.password_param) && rodauth.features.include?(:reset_password) %>
  <%= render template: "rodauth/reset_password_request", layout: false %>
<% end %>

app/views/rodauth/change_login.html.erb
<%= form_with url: rodauth.change_login_path, method: :post, data: { turbo: false }, class: "w-full max-w-sm" do |form| %>
  <div class="mb-6">
    <%= form.label "login", rodauth.login_label, class: "block text-sm font-semibold" %>
    <%= form.email_field rodauth.login_param, value: params[rodauth.login_param], id: "login", autocomplete: "email", required: true, class: "mt-2 text-sm w-full px-3 py-2 border rounded-md dark:bg-gray-900 dark:text-gray-100 dark:focus:bg-gray-800 #{rodauth.field_error(rodauth.login_param) ? "border-red-600 focus:ring-red-600 focus:border-red-600 dark:border-red-400 dark:focus:ring-red-400" : "border-gray-300 dark:border-gray-700 dark:focus:border-emerald-400 dark:focus:ring-emerald-400" }", aria: ({ invalid: true, describedby: "login_error_message" } if rodauth.field_error(rodauth.login_param)) %>
    <%= content_tag(:span, rodauth.field_error(rodauth.login_param), class: "block mt-1 text-red-600 text-xs dark:text-red-400", id: "login_error_message") if rodauth.field_error(rodauth.login_param) %>
  </div>

  <% if rodauth.require_login_confirmation? %>
    <div class="mb-6">
      <%= form.label "login-confirm", rodauth.login_confirm_label, class: "block text-sm font-semibold" %>
      <%= form.email_field rodauth.login_confirm_param, value: params[rodauth.login_confirm_param], id: "login-confirm", autocomplete: "email", required: true, class: "mt-2 text-sm w-full px-3 py-2 border rounded-md dark:bg-gray-900 dark:text-gray-100 dark:focus:bg-gray-800 #{rodauth.field_error(rodauth.login_confirm_param) ? "border-red-600 focus:ring-red-600 focus:border-red-600 dark:border-red-400 dark:focus:ring-red-400" : "border-gray-300 dark:border-gray-700 dark:focus:border-emerald-400 dark:focus:ring-emerald-400" }", aria: ({ invalid: true, describedby: "login-confirm_error_message" } if rodauth.field_error(rodauth.login_confirm_param)) %>
      <%= content_tag(:span, rodauth.field_error(rodauth.login_confirm_param), class: "block mt-1 text-red-600 text-xs dark:text-red-400", id: "login-confirm_error_message") if rodauth.field_error(rodauth.login_confirm_param) %>
    </div>
  <% end %>

  <% if rodauth.change_login_requires_password? %>
    <div class="mb-6">
      <%= form.label "password", rodauth.password_label, class: "block text-sm font-semibold" %>
      <%= form.password_field rodauth.password_param, value: "", id: "password", autocomplete: rodauth.password_field_autocomplete_value, required: true, class: "mt-2 text-sm w-full px-3 py-2 border rounded-md dark:bg-gray-900 dark:text-gray-100 dark:focus:bg-gray-800 #{rodauth.field_error(rodauth.password_param) ? "border-red-600 focus:ring-red-600 focus:border-red-600 dark:border-red-400 dark:focus:ring-red-400" : "border-gray-300 dark:border-gray-700 dark:focus:border-emerald-400 dark:focus:ring-emerald-400" }", aria: ({ invalid: true, describedby: "password_error_message" } if rodauth.field_error(rodauth.password_param)) %>
      <%= content_tag(:span, rodauth.field_error(rodauth.password_param), class: "block mt-1 text-red-600 text-xs dark:text-red-400", id: "password_error_message") if rodauth.field_error(rodauth.password_param) %>
    </div>
  <% end %>

  <%= form.submit rodauth.change_login_button, class: "w-full px-8 py-3 cursor-pointer font-semibold text-sm rounded-md text-white bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-600 dark:bg-emerald-400 dark:hover:bg-emerald-500 dark:text-gray-900 dark:focus:ring-emerald-400 dark:focus:ring-offset-current" %>
<% end %>

app/views/rodauth/close_account.html.erb
<%= form_with url: rodauth.close_account_path, method: :post, data: { turbo: false }, class: "w-full max-w-sm" do |form| %>
  <% if rodauth.close_account_requires_password? %>
    <div class="mb-6">
      <%= form.label "password", rodauth.password_label, class: "block text-sm font-semibold" %>
      <%= form.password_field rodauth.password_param, value: "", id: "password", autocomplete: rodauth.password_field_autocomplete_value, required: true, class: "mt-2 text-sm w-full px-3 py-2 border rounded-md dark:bg-gray-900 dark:text-gray-100 dark:focus:bg-gray-800 #{rodauth.field_error(rodauth.password_param) ? "border-red-600 focus:ring-red-600 focus:border-red-600 dark:border-red-400 dark:focus:ring-red-400" : "border-gray-300 dark:border-gray-700 dark:focus:border-emerald-400 dark:focus:ring-emerald-400" }", aria: ({ invalid: true, describedby: "password_error_message" } if rodauth.field_error(rodauth.password_param)) %>
      <%= content_tag(:span, rodauth.field_error(rodauth.password_param), class: "block mt-1 text-red-600 text-xs dark:text-red-400", id: "password_error_message") if rodauth.field_error(rodauth.password_param) %>
    </div>
  <% end %>

  <%= form.submit rodauth.close_account_button, class: "w-full px-8 py-3 cursor-pointer font-semibold text-sm rounded-md text-white bg-red-600 hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-600 dark:bg-red-400 dark:hover:bg-red-500 dark:text-gray-900 dark:focus:ring-red-400 dark:focus:ring-offset-current" %>
<% end %>

app/views/rodauth/login.html.erb
<div class="flex-1 space-y-4">
  <%= render "login_form_header" %>
  <%= render "login_form" %>
  <%= render "login_form_footer" %>
</div>

app/views/rodauth/logout.html.erb
<%= form_with url: rodauth.logout_path, method: :post, data: { turbo: false }, class: "w-full max-w-sm" do |form| %>
  <% if rodauth.features.include?(:active_sessions) %>
    <div class="mb-6 flex items-center space-x-2">
      <%= form.check_box rodauth.global_logout_param, id: "global-logout", class: "rounded dark:bg-gray-900 dark:border-gray-600 dark:checked:bg-current dark:checked:border-current dark:checked:text-emerald-400 dark:focus:ring-emerald-400 dark:focus:ring-offset-gray-900", include_hidden: false %>
      <%= form.label "global-logout", rodauth.global_logout_label, class: "text-sm" %>
    </div>
  <% end %>

  <%= form.submit rodauth.logout_button, class: "w-full px-8 py-3 cursor-pointer font-semibold text-sm rounded-md bg-yellow-300 hover:bg-yellow-400 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-yellow-300 dark:bg-violet-400 dark:hover:bg-violet-500 dark:text-gray-900 dark:focus:ring-violet-400 dark:focus:ring-offset-current" %>
<% end %>

app/views/rodauth/multi_phase_login.html.erb
<div class="flex-1 space-y-4">
  <%= render "login_form_header" %>
  <%== rodauth.render_multi_phase_login_forms %>
  <%= render "login_form_footer" %>
</div>

app/views/rodauth/verify_login_change.html.erb
<%= form_with url: rodauth.verify_login_change_path, method: :post, data: { turbo: false }, class: "w-full max-w-sm" do |form| %>
  <%= form.submit rodauth.verify_login_change_button, class: "w-full px-8 py-3 cursor-pointer font-semibold text-sm rounded-md text-white bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-600 dark:bg-emerald-400 dark:hover:bg-emerald-500 dark:text-gray-900 dark:focus:ring-emerald-400 dark:focus:ring-offset-current" %>
<% end %>

app/views/stocks/_form.html.erb
<%= form_with(model: stock, class: "contents") do |form| %>
  <% if stock.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(stock.errors.count, "error") %> prohibited this stock from being saved:</h2>

      <ul>
        <% stock.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/stocks/_search_form.html.erb
<div class="relative mt-2 flex items-center">
<%= search_form_for @q do |f|%>
  <%= f.search_field :product_name_cont, placeholder: "search", class: "block w-full rounded-md border-0 py-1.5 pr-12 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" %>
<%end%>
</div>

app/views/stocks/_stock.html.erb
<div id="<%= dom_id stock %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Product name:</strong>
    <%= stock.product_name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Description:</strong>
    <%= stock.description %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Quantity:</strong>
    <%= stock.quantity %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Price:</strong>
    <%= stock.price %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this stock", stock, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this stock', edit_stock_path(stock), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/stocks/index.html.erb
<% content_for(:header) do %>
    <%= render Dashboard::PageHeaderComponent.new(title: "Stocks",link: Link.new("Add Stocks", new_stock_path ),q: @q ) %>
<%end%>
<% content_for(:content) do %>


<div class="px-4 sm:px-6 lg:px-8">
  <div class="mt-8 flow-root">
    <div class="-my-2 -mx-4 overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div class="inline-block min-w-full py-2 align-middle sm:px-6 lg:px-8">
        <div class="overflow-hidden shadow ring-1 ring-black ring-opacity-5 sm:rounded-lg">
          <table class="min-w-full divide-y divide-gray-300">
            <thead class="bg-gray-50">
              <tr>
                <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-6">Product name</th>
                <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Description</th>
                <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Quantity</th>
                <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Price</th>
                <th scope="col" class="relative py-3.5 pl-3 pr-4 sm:pr-6">
                  <span class="sr-only">Action</span>
                </th>
              </tr>
            </thead>
            <tbody class="divide-y divide-gray-200 bg-white">
              <%= render Content::StockComponent.with_collection(@stocks) %>

              <!-- More people... -->
            </tbody>
          </table>



          <nav class="flex items-center justify-between border-t border-gray-200 bg-white px-4 py-3 sm:px-6" aria-label="Pagination">
            <div class="hidden sm:block">
              <p class="text-sm text-gray-700">
                <%= page_entries_info @stocks, entry_name: 'item'%>
              </p>
            </div>
            <div class="flex flex-1 justify-between sm:justify-end">
              <%= link_to_next_page @stocks, 'Previous', class: "relative inline-flex items-center rounded-md bg-white px-3 py-2 text-sm font-semibold text-gray-900 ring-1 ring-inset ring-gray-300 hover:bg-gray-50 focus-visible:outline-offset-0"%>
              <%= link_to_previous_page @stocks, 'Next', class: "relative ml-3 inline-flex items-center rounded-md bg-white px-3 py-2 text-sm font-semibold text-gray-900 ring-1 ring-inset ring-gray-300 hover:bg-gray-50 focus-visible:outline-offset-0"%>
            </div>
          </nav>

        </div>
      </div>
    </div>
  </div>
</div>
<%end%>

app/views/stocks/show.html.erb
<% content_for(:header) do %>
    <%= render Dashboard::PageHeaderComponent.new(title: @stock.product_name) %>
<%end%>

<% content_for(:content) do %>
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @stock %>

    <%= link_to 'Edit this stock', edit_stock_path(@stock), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this stock', stock_path(@stock), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to stocks', stocks_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>
<%end%>